server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5tDAkYyD47d7GAZ5Txrx
    keySecret: MgIATZH6ZMrviQCB1mI2hnmDicvO03
    bucketName: srb-file-xyf